name: Code Style Check

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  codestyle:
    name: Run code style check
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Check out source code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Set up PHP
        uses: shivammathur/setup-php@a4e22b60bbb9c1021113f2860347b0759f66fe5d # 2.30.0
        with:
          php-version: "8.0"
          coverage: none
        env:
          fail-fast: 'true'

      - name: Install dependencies
        uses: ramsey/composer-install@57532f8be5bda426838819c5ee9afb8af389d51a # 3.0.0

      - name: Add error matcher
        run: echo "::add-matcher::$(pwd)/.github/checkstyle-problem-matcher.json"

      - name: Run style check
        run: composer phpcs -- --report=checkstyle
